## 📓 Notebook 01: Load & Explore

**Skills practiced:** `.info()`, checking target class balance with `value_counts(normalize=True)`.

**Goal:** Load the lending dataset and record the exact default/no-default class balance — this number matters later when judging accuracy.

In [88]:
import pandas as pd

path='../data/raw/raw_loan_data.csv'
cols = ['title', 'loan_amnt', 'int_rate', 'dti', 'revol_util','open_acc','installment','emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'loan_status']
df=pd.read_csv(path, usecols=cols)
df=df.rename(columns={'title':'purpose'})
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   loan_amnt       float64
 1   int_rate        float64
 2   installment     float64
 3   emp_title       str
 4   emp_length      str
 5   home_ownership  str
 6   annual_inc      float64
 7   loan_status     str
 8   purpose         str
 9   dti             float64
 10  open_acc        float64
 11  revol_util      float64
dtypes: float64(7), str(5)
memory usage: 325.1 MB

,loan_amnt,int_rate,installment,emp_title,emp_length,home_ownership,annual_inc,loan_status,purpose,dti,open_acc,revol_util
0,3600.0,13.99,123.03,leadman,10+ years,MORTGAGE,55000.0,Fully Paid,Debt consolidation,5.91,7.0,29.7
1,24700.0,11.99,820.28,Engineer,10+ years,MORTGAGE,65000.0,Fully Paid,Business,16.06,22.0,19.2
2,20000.0,10.78,432.66,truck driver,10+ years,MORTGAGE,63000.0,Fully Paid,NaN,10.78,6.0,56.2
3,35000.0,14.85,829.90,Information Systems Officer,10+ years,MORTGAGE,110000.0,Current,Debt consolidation,17.06,13.0,11.6
4,10400.0,22.45,289.91,Contract Specialist,3 years,MORTGAGE,104433.0,Fully Paid,Major purchase,25.37,12.0,64.5

In [89]:

df.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,open_acc,revol_util
count,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260639e+06,2.258866e+06
mean,1.504693e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,1.161240e+01,5.033770e+01
std,9.190245e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,5.640861e+00,2.471307e+01
min,5.000000e+02,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00
25%,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,8.000000e+00,3.150000e+01
50%,1.290000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,1.100000e+01,5.030000e+01
75%,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,1.400000e+01,6.940000e+01
max,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,1.010000e+02,8.923000e+02

In [90]:
df.groupby('loan_status')['emp_title'].count()

loan_status
Charged Off                                             246098
Current                                                 800493
Default                                                     34
Does not meet the credit policy. Status:Charged Off        711
Does not meet the credit policy. Status:Fully Paid        1879
Fully Paid                                             1013427
In Grace Period                                           7764
Late (16-30 days)                                         3845
Late (31-120 days)                                       19448
Name: emp_title, dtype: int64

In [91]:
df = df[df["loan_status"].isin([
    "Fully Paid",
    "Charged Off",
    "Does not meet the credit policy. Status:Charged Off",
    "Default"
])]

In [92]:
df['defaulted']=(df['loan_status'].isin(['Default',
                                        'Does not meet the credit policy. Status:Charged Off',
                                        'Charged Off'])).astype(int)

In [93]:
print(df['defaulted'].value_counts(normalize=True))
df.to_csv('../data/processed/loans_cleaned.csv', index=False)

defaulted
0    0.799898
1    0.200102
Name: proportion, dtype: float64